sudo: required
services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t jskinner9999/docker-react .

script: 
  - docker run -e CI=true -t jskinner9999/docker-react npm run test



  